# Generated by Django 6.0 on 2026-01-05 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelUSACO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=50, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de dificuldade')),
            ],
            options={
                'verbose_name': 'Nível USACO',
                'verbose_name_plural': 'Níveis USACO',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ModuloTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('link_aula', models.URLField(blank=True, help_text='Link para o USACO Guide ou aula', max_length=500)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.nivelusaco')),
            ],
            options={
                'verbose_name': 'Módulo Teórico',
                'verbose_name_plural': 'Módulos Teóricos',
                'ordering': ['nivel', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_codeforces', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('handle_atcoder', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('rating_atual', models.IntegerField(default=0)),
                ('total_solved', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('problema_id', models.CharField(help_text='Ex: 1980A, abc340_a', max_length=100)),
                ('plataforma', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder'), ('OJ', 'Outros')], max_length=2)),
                ('link', models.URLField(max_length=500)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemas', to='core.moduloteorico')),
            ],
        ),
        migrations.CreateModel(
            name='SolucaoCompartilhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Cole seu código aqui')),
                ('linguagem', models.CharField(default='C++', help_text='Linguagem utilizada', max_length=50)),
                ('data_postagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('votos_uteis', models.PositiveIntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucoes', to='core.perfilaluno')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucoes_alunos', to='core.problemareferencia')),
            ],
            options={
                'verbose_name': 'Solução Compartilhada',
                'ordering': ['-data_postagem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Maratona Iniciante', max_length=100)),
                ('semestre', models.CharField(help_text='Ex: 2024.1', max_length=20)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'unique_together': {('nome', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma'),
        ),
        migrations.CreateModel(
            name='ProgressoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teoria_lida', models.BooleanField(default=False)),
                ('todos_problemas_resolvidos', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_modulos', to='core.perfilaluno')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_alunos', to='core.moduloteorico')),
            ],
            options={
                'verbose_name': 'Progresso no Módulo',
                'unique_together': {('aluno', 'modulo')},
            },
        ),
    ]
