# Generated by Django 6.0 on 2026-01-05 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=10)),
                ('contest_id', models.CharField(max_length=50)),
                ('problem_index', models.CharField(max_length=10)),
                ('verdict', models.CharField(max_length=50)),
                ('submission_time', models.DateTimeField()),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['-submission_time'],
                'indexes': [models.Index(fields=['contest_id', 'problem_index'], name='core_submis_contest_56ea36_idx'), models.Index(fields=['submission_time'], name='core_submis_submiss_7e800c_idx')],
            },
        ),
    ]
