# Generated by Codex on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissao',
            name='problem_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submissao',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='submissao',
            index=models.Index(
                fields=['plataforma', 'contest_id', 'problem_index'],
                name='core_submis_platafo_76be9d_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='submissao',
            constraint=models.UniqueConstraint(
                condition=models.Q(external_id__isnull=False),
                fields=('plataforma', 'external_id'),
                name='core_submissao_platform_external_id_uniq',
            ),
        ),
    ]
