# Generated by Django 6.0 on 2026-01-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submissao_metadata_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRatingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2)),
                ('problem_url', models.URLField(max_length=500, unique=True)),
                ('clist_problem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('clist_rating', models.IntegerField(blank=True, null=True)),
                ('rating_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('rating_source', models.CharField(default='clist_api_v4', max_length=50)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NOT_FOUND', 'Not Found'), ('TEMP_FAIL', 'Temporary Failure')], default='OK', max_length=20)),
            ],
            options={
                'verbose_name': 'Problem Rating Cache',
                'verbose_name_plural': 'Problem Rating Cache',
                'indexes': [models.Index(fields=['platform', 'status'], name='core_proble_platfor_ec406f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserScoreAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_cf_total', models.IntegerField(default=0)),
                ('points_ac_total', models.IntegerField(default=0)),
                ('points_total', models.IntegerField(default=0)),
                ('points_last_7d', models.IntegerField(default=0)),
                ('points_last_30d', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_agg', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'User Score Aggregate',
                'verbose_name_plural': 'User Score Aggregates',
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2)),
                ('problem_url', models.URLField(max_length=500)),
                ('solved_at', models.DateTimeField()),
                ('raw_rating', models.IntegerField(blank=True, null=True)),
                ('normalized_rating', models.FloatField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('reason', models.CharField(default='first_ac', max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='core.perfilaluno')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_event', to='core.submissao')),
            ],
            options={
                'verbose_name': 'Score Event',
                'verbose_name_plural': 'Score Events',
                'indexes': [models.Index(fields=['aluno', 'platform'], name='core_scoree_aluno_i_76ec56_idx'), models.Index(fields=['solved_at'], name='core_scoree_solved__50415c_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'platform', 'problem_url'), name='scoreevent_first_solve_unique')],
            },
        ),
    ]
