# Generated by Django 6.0 on 2026-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_problemratingcache_userscoreagg_scoreevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRatingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2, unique=True)),
                ('median', models.FloatField()),
                ('iqr', models.FloatField()),
                ('sample_size', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Rating Stats',
                'verbose_name_plural': 'Platform Rating Stats',
            },
        ),
    ]
