# Generated by Django 6.0 on 2026-01-12 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platformratingstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('TURMA', 'Turma')], max_length=10)),
                ('category', models.CharField(choices=[('TOTAL', 'Geral'), ('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=5)),
                ('window', models.CharField(choices=[('ALL', 'All-time'), ('7D', 'Last 7 days'), ('30D', 'Last 30 days')], max_length=5)),
                ('rank', models.PositiveIntegerField()),
                ('points', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_snapshots', to='core.perfilaluno')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma')),
            ],
            options={
                'verbose_name': 'User Rank Snapshot',
                'verbose_name_plural': 'User Rank Snapshots',
                'indexes': [models.Index(fields=['scope', 'category', 'window', 'snapshot_date'], name='core_userra_scope_e5872e_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'scope', 'turma', 'category', 'window', 'snapshot_date'), name='user_rank_snapshot_unique')],
            },
        ),
    ]
