# Generated by Django 6.0 on 2026-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userranksnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreevent',
            name='percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='points_ac_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='points_cf_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='points_general_norm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='unified_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_ac_30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_ac_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_ac_raw_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_cf_30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_cf_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_cf_raw_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_norm_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='season_points_ac_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='season_points_cf_raw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='season_points_general_norm',
            field=models.IntegerField(default=0),
        ),
    ]
