# Generated by Django 6.0 on 2026-01-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scoreevent_percentile_scoreevent_points_ac_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userranksnapshot',
            name='window',
            field=models.CharField(choices=[('ALL', 'All-time'), ('7D', 'Last 7 days'), ('30D', 'Last 30 days'), ('SEASON', 'Season')], max_length=10),
        ),
    ]
