# Generated by Django 6.0 on 2026-01-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userranksnapshot_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilaluno',
            name='ac_rating_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='ac_rating_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='ac_rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='cf_rating_current',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='cf_rating_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilaluno',
            name='cf_rating_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
