# Generated by Django 6.0 on 2026-01-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilaluno_ac_rating_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2)),
                ('contest_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('category', models.CharField(choices=[('ABC', 'ABC'), ('ARC', 'ARC'), ('AGC', 'AGC'), ('AHC', 'AHC'), ('Other', 'Other')], db_index=True, default='Other', max_length=10)),
                ('division', models.CharField(choices=[('Div1', 'Div1'), ('Div2', 'Div2'), ('Div3', 'Div3'), ('Div4', 'Div4'), ('Educational', 'Educational'), ('Global', 'Global'), ('Other', 'Other')], db_index=True, default='Other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
                'indexes': [models.Index(fields=['platform', 'start_time'], name='core_contes_platfor_9002da_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'contest_id'), name='contest_platform_contest_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(db_index=True)),
                ('index_label', models.CharField(max_length=20)),
                ('problem_url', models.URLField(db_index=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='core.contest')),
            ],
            options={
                'verbose_name': 'Contest Problem',
                'verbose_name_plural': 'Contest Problems',
                'indexes': [models.Index(fields=['contest', 'order'], name='core_contes_contest_08a80e_idx')],
                'constraints': [models.UniqueConstraint(fields=('contest', 'problem_url'), name='contest_problem_unique')],
            },
        ),
    ]
