# Generated by Django 6.0 on 2026-01-21 18:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contest_contestproblem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2)),
                ('problem_url', models.URLField(default='', max_length=500)),
                ('contest_platform', models.CharField(blank=True, choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2, null=True)),
                ('contest_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission Proof',
                'verbose_name_plural': 'Submission Proofs',
            },
        ),
        migrations.AlterModelOptions(
            name='solucaocompartilhada',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solução Compartilhada', 'verbose_name_plural': 'Soluções Compartilhadas'},
        ),
        migrations.RemoveField(
            model_name='solucaocompartilhada',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='solucaocompartilhada',
            name='data_postagem',
        ),
        migrations.RemoveField(
            model_name='solucaocompartilhada',
            name='linguagem',
        ),
        migrations.RemoveField(
            model_name='solucaocompartilhada',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='solucaocompartilhada',
            name='votos_uteis',
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_solutions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='code_text',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(200000)]),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='contest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='idea_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C#', 'C#'), ('JavaScript', 'JavaScript'), ('Go', 'Go'), ('Rust', 'Rust'), ('Kotlin', 'Kotlin'), ('Other', 'Other')], default='C++', max_length=30),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='platform_context',
            field=models.CharField(blank=True, choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='problem_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solucaocompartilhada',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('class', 'Class'), ('public', 'Public')], default='class', max_length=10),
        ),
        migrations.AddIndex(
            model_name='solucaocompartilhada',
            index=models.Index(fields=['problem_url'], name='core_soluca_problem_e2835d_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaocompartilhada',
            index=models.Index(fields=['aluno', 'problem_url'], name='core_soluca_aluno_i_770712_idx'),
        ),
        migrations.AddIndex(
            model_name='solucaocompartilhada',
            index=models.Index(fields=['contest_id'], name='core_soluca_contest_dfea32_idx'),
        ),
        migrations.AddConstraint(
            model_name='solucaocompartilhada',
            constraint=models.UniqueConstraint(fields=('aluno', 'problem_url'), name='solucao_unique_per_problem'),
        ),
        migrations.AddField(
            model_name='submissionproof',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_proofs', to='core.perfilaluno'),
        ),
        migrations.AddIndex(
            model_name='submissionproof',
            index=models.Index(fields=['problem_url'], name='core_submis_problem_f02e49_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionproof',
            index=models.Index(fields=['aluno', 'problem_url'], name='core_submis_aluno_i_dd3693_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionproof',
            index=models.Index(fields=['contest_id'], name='core_submis_contest_deba5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionproof',
            constraint=models.UniqueConstraint(fields=('aluno', 'platform', 'problem_url'), name='submissionproof_unique_per_problem'),
        ),
    ]
