# Generated by Django 6.0 on 2026-01-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submissionproof_alter_solucaocompartilhada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solucaocompartilhada',
            name='language',
            field=models.CharField(
                choices=[
                    ('cpp', 'C++17/20'),
                    ('c', 'C'),
                    ('py', 'Python'),
                    ('java', 'Java'),
                    ('js', 'JavaScript'),
                    ('ts', 'TypeScript'),
                    ('go', 'Go'),
                    ('rust', 'Rust'),
                    ('kt', 'Kotlin'),
                    ('cs', 'C#'),
                ],
                default='cpp',
                max_length=30,
            ),
        ),
    ]
