# Generated by Django 6.0 on 2026-01-27 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solucaocompartilhada_language_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingConversionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('AC_TO_CF', 'AC_TO_CF'), ('CF_TO_AC', 'CF_TO_AC')], max_length=20)),
                ('method', models.CharField(choices=[('bin_mean_monotone_v1', 'bin_mean_monotone_v1')], max_length=30)),
                ('source_population', models.CharField(choices=[('internal_users', 'internal_users')], max_length=30)),
                ('min_pair_count', models.IntegerField(default=200)),
                ('min_activity_rules_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rating Conversion Model',
                'verbose_name_plural': 'Rating Conversion Models',
            },
        ),
        migrations.CreateModel(
            name='RatingConversionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_rating', models.IntegerField()),
                ('y_rating', models.IntegerField()),
                ('sample_n', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rating Conversion Point',
                'verbose_name_plural': 'Rating Conversion Points',
            },
        ),
        migrations.CreateModel(
            name='RatingConversionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField()),
                ('pairs_used', models.IntegerField()),
                ('mae', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rating Conversion Snapshot',
                'verbose_name_plural': 'Rating Conversion Snapshots',
            },
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='bonus_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='contest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='contest_platform',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='in_contest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='points_general_cf_equiv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='rating_used_cf_equiv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='mode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='scope_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userranksnapshot',
            name='window_key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_cf_equiv_30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_cf_equiv_7d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='points_general_cf_equiv_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscoreagg',
            name='season_points_general_cf_equiv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perfilaluno',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submissionproof',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='scoreevent',
            index=models.Index(fields=['problem_url'], name='core_scoree_problem_16f4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='userranksnapshot',
            index=models.Index(fields=['mode', 'source', 'window_key', 'scope_key', 'snapshot_date'], name='core_userra_mode_53f2c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='userranksnapshot',
            constraint=models.UniqueConstraint(fields=('mode', 'source', 'window_key', 'scope_key', 'snapshot_date', 'aluno'), name='user_rank_snapshot_unique_v2'),
        ),
        migrations.AddField(
            model_name='ratingconversionpoint',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.ratingconversionmodel'),
        ),
        migrations.AddField(
            model_name='ratingconversionsnapshot',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.ratingconversionmodel'),
        ),
        migrations.AddIndex(
            model_name='ratingconversionpoint',
            index=models.Index(fields=['model', 'x_rating'], name='core_rating_model_i_03fadd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratingconversionpoint',
            constraint=models.UniqueConstraint(fields=('model', 'x_rating'), name='rating_conversion_point_unique'),
        ),
    ]
