# Generated by Django 6.0 on 2026-01-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ratingconversionmodel_ratingconversionpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems_next_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems_sync_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems_sync_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SYNCED', 'SYNCED'), ('STALE', 'STALE'), ('FAILED', 'FAILED')], db_index=True, default='NEW', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='ratings_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='ratings_ready_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='ratings_summary_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PARTIAL', 'PARTIAL'), ('READY', 'READY')], db_index=True, default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='ratings_total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='platform',
            field=models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], db_index=True, default='CF', max_length=2),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='rating_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='rating_last_ok_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='rating_last_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='rating_status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('QUEUED', 'Queued'), ('OK', 'OK'), ('NOT_FOUND', 'Not Found'), ('TEMP_FAIL', 'Temporary Failure')], db_index=True, default='MISSING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['platform', 'year'], name='core_contes_platfor_ebd556_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['problems_sync_status', 'problems_next_sync_at'], name='core_contes_problem_30e9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='contestproblem',
            index=models.Index(fields=['contest', 'rating_status'], name='core_contes_contest_4797a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contestproblem',
            index=models.Index(fields=['platform', 'rating_status'], name='core_contes_platfor_888e27_idx'),
        ),
    ]
