# Generated by Codex on 2026-01-28

from django.db import migrations


def backfill_contestproblem_platform(apps, schema_editor):
    ContestProblem = apps.get_model("core", "ContestProblem")
    Contest = apps.get_model("core", "Contest")
    contest_platforms = dict(Contest.objects.values_list("id", "platform"))
    batch = []
    for problem in ContestProblem.objects.all().only("id", "contest_id", "platform"):
        platform = contest_platforms.get(problem.contest_id)
        if platform and problem.platform != platform:
            problem.platform = platform
            batch.append(problem)
        if len(batch) >= 500:
            ContestProblem.objects.bulk_update(batch, ["platform"])
            batch = []
    if batch:
        ContestProblem.objects.bulk_update(batch, ["platform"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_contest_sync_state"),
    ]

    operations = [
        migrations.RunPython(backfill_contestproblem_platform, migrations.RunPython.noop),
    ]
