# Generated by Django 6.0 on 2026-02-06 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_season_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtCoderRatingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_rating_snapshots', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'AtCoder Rating Snapshot',
                'verbose_name_plural': 'AtCoder Rating Snapshots',
                'indexes': [models.Index(fields=['aluno', 'date'], name='core_atcode_aluno_i_c5520f_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'date'), name='ac_rating_snapshot_aluno_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='CodeforcesRatingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.CharField(max_length=50)),
                ('contest_name', models.CharField(blank=True, max_length=255)),
                ('rating_old', models.IntegerField()),
                ('rating_new', models.IntegerField()),
                ('rating_update_time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_rating_changes', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'Codeforces Rating Change',
                'verbose_name_plural': 'Codeforces Rating Changes',
                'indexes': [models.Index(fields=['aluno', 'rating_update_time'], name='core_codefo_aluno_i_e227f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'contest_id'), name='cf_rating_change_aluno_contest_unique')],
            },
        ),
    ]
