# Generated by Django 6.0 on 2026-02-08 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_atcoderratingsnapshot_codeforcesratingchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('consistency', 'Consistência'), ('evolution', 'Evolução'), ('challenge', 'Desafio')], db_index=True, default='evolution', max_length=20)),
                ('target_minutes', models.PositiveIntegerField(default=90)),
                ('objective', models.CharField(blank=True, default='2 CF + 2 AC', max_length=200)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], db_index=True, max_length=2)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('problem_url', models.URLField(max_length=500)),
                ('contest_id', models.CharField(blank=True, max_length=50, null=True)),
                ('index_label', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('result', models.CharField(choices=[('TODO', 'Todo'), ('SOLVED', 'Resolvi'), ('EDITORIAL', 'Usei editorial'), ('STUCK', 'Travei'), ('SKIPPED', 'Adiei'), ('BLOCKED', 'Bloqueei')], db_index=True, default='TODO', max_length=20)),
                ('stuck_reason', models.CharField(blank=True, choices=[('idea', 'Ideia'), ('implementation', 'Implementação'), ('math', 'Matemática'), ('reading', 'Leitura'), ('edge_cases', 'Edge cases')], max_length=20, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.trainingsession')),
            ],
            options={
                'verbose_name': 'Training Session Item',
                'verbose_name_plural': 'Training Session Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingBlockedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], db_index=True, max_length=2)),
                ('problem_url', models.URLField(max_length=500)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_blocked', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'Training Blocked Problem',
                'verbose_name_plural': 'Training Blocked Problems',
                'indexes': [models.Index(fields=['aluno', 'platform'], name='core_traini_aluno_i_ddacee_idx'), models.Index(fields=['problem_url'], name='core_traini_problem_b8827c_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'platform', 'problem_url'), name='training_block_unique_problem')],
            },
        ),
        migrations.CreateModel(
            name='TrainingQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], db_index=True, max_length=2)),
                ('problem_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('QUEUED', 'Na fila'), ('DONE', 'Concluído'), ('BLOCKED', 'Bloqueado')], db_index=True, default='QUEUED', max_length=20)),
                ('source', models.CharField(choices=[('cf_suggest', 'Sugestão CF'), ('ac_suggest', 'Sugestão AC'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_queue', to='core.perfilaluno')),
            ],
            options={
                'verbose_name': 'Training Queue Item',
                'verbose_name_plural': 'Training Queue Items',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['aluno', 'status', 'priority'], name='core_traini_aluno_i_d28442_idx')],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'platform', 'problem_url'), name='training_queue_unique_problem')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['aluno', 'is_active', 'started_at'], name='core_traini_aluno_i_e78143_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionitem',
            index=models.Index(fields=['session', 'order'], name='core_traini_session_9578d1_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionitem',
            index=models.Index(fields=['session', 'result'], name='core_traini_session_0abed0_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingsessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'platform', 'problem_url'), name='training_session_item_unique_problem'),
        ),
    ]
