# Generated by Django 6.0 on 2026-02-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contestproblem_tags_trainingsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='mode',
            field=models.CharField(choices=[('consistency', 'Consistência'), ('general', 'Geral'), ('evolution', 'Evolução'), ('challenge', 'Desafio')], db_index=True, default='evolution', max_length=20),
        ),
    ]
