# Generated by Django 6.0 on 2026-02-09 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_trainingsession_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_gym',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='cf_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='attempts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='cf_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='effective_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainingsessionitem',
            name='expected_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsessionitem',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsessionitem',
            name='origin',
            field=models.CharField(blank=True, default='normal_suggestion', max_length=30),
        ),
        migrations.AlterField(
            model_name='problemratingcache',
            name='rating_source',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemratingcache',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('NOT_FOUND', 'Not Found'), ('TEMP_FAIL', 'Temporary Failure'), ('RATE_LIMITED', 'Rate Limited'), ('ERROR', 'Error')], default='OK', max_length=20),
        ),
        migrations.CreateModel(
            name='RatingFetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('CF', 'Codeforces'), ('AC', 'AtCoder')], db_index=True, max_length=2)),
                ('problem_url', models.URLField(max_length=500)),
                ('priority', models.IntegerField(choices=[(0, 'High'), (1, 'Low')], db_index=True, default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=10)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rating Fetch Job',
                'verbose_name_plural': 'Rating Fetch Jobs',
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='core_rating_status_f0e178_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'problem_url'), name='rating_fetch_job_unique_problem')],
            },
        ),
    ]
