# Generated by Django 6.0 on 2026-02-11 13:02

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contest_is_gym_contest_last_sync_at_contest_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#22C55E', max_length=7, validators=[django.core.validators.RegexValidator(message='Use uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_villain', models.BooleanField(default=False, help_text='Se marcado, os membros deste grupo nao aparecem no ranking.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='competitor_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo Competitivo',
                'verbose_name_plural': 'Grupos Competitivos',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
