# Generated by Django 6.0 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_competitorgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilaluno",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("signup", "Cadastro"),
                    ("admin", "Adicionado pelo ADM"),
                    ("legacy", "Legado"),
                ],
                db_index=True,
                default="legacy",
                max_length=12,
            ),
        ),
    ]
