# Generated by Django 6.0 on 2026-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_perfilaluno_created_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemratingcache',
            name='provisional_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='provisional_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='provisional_source',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='problemratingcache',
            name='provisional_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='rating_is_provisional',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scoreevent',
            name='rating_source',
            field=models.CharField(db_index=True, default='none', max_length=20),
        ),
    ]
