from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='index'), # Redireciona o index para o dashboard
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('me/', views.me_view, name='me'),
    path('me/refresh-ratings/', views.refresh_my_ratings, name='refresh_my_ratings'),
    path('u/<str:username>/refresh-ratings/', views.refresh_user_ratings, name='refresh_user_ratings'),
    path('me/password/', views.change_password_view, name='change_password'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-panel/users/', views.admin_users, name='admin_users'),
    path('admin-panel/users/<int:user_id>/promote/', views.admin_user_promote, name='admin_user_promote'),
    path('admin-panel/users/<int:user_id>/delete/', views.admin_user_delete, name='admin_user_delete'),
    path('contests/force/<str:platform>/<str:contest_id>/', views.force_contest_sync, name='force_contest_sync'),
    path(
        'contests/snippet/card/<str:platform>/<str:contest_id>/',
        views.contest_card_snippet,
        name='contest_card_snippet',
    ),
    path('dashboard/activity/', views.dashboard_activity, name='dashboard_activity'),
    path('tour/next/', views.welcome_tour_next, name='welcome_tour_next'),
    path('tour/skip/', views.welcome_tour_skip, name='welcome_tour_skip'),
    path('u/<str:username>/', views.user_profile, name='user_profile'),
    path('u/<str:username>/tab/<str:tab>/', views.user_profile_tab, name='user_profile_tab'),
    path('u/<str:username>/activity/heatmap/', views.user_profile_heatmap, name='user_profile_heatmap'),
    path('aluno/<str:username>/', views.perfil_aluno, name='perfil_aluno'),
    path('add-student/', views.add_student, name='add_student'),
    path('submissao/<int:submission_id>/solution/', views.solution_modal, name='solution_modal'),
    path('solutions/modal/', views.solutions_modal, name='solutions_modal'),
    path('solutions/save/', views.solutions_save, name='solutions_save'),
    path('solutions/format/', views.solutions_format, name='solutions_format'),
    path('solutions/view/', views.solutions_view, name='solutions_view'),
    path('solutions/approve/', views.solutions_approve, name='solutions_approve'),
    path('ranking/', views.ranking, name='ranking'),
    path('ranking/list/', views.ranking_list, name='ranking_list'),
    path('treino/', views.train, name='train'),
    path('treino/session/start/', views.train_session_start, name='train_session_start'),
    path('treino/session/<int:session_id>/', views.train_session, name='train_session'),
    path('treino/session/<int:session_id>/end/', views.train_session_end, name='train_session_end'),
    path('treino/session/<int:session_id>/item/<int:item_id>/result/', views.train_session_item_result, name='train_session_item_result'),
    path('treino/upsolving/add/', views.train_upsolving_add, name='train_upsolving_add'),
    path('treino/queue/add/', views.train_queue_add, name='train_queue_add'),
    path('treino/queue/<int:item_id>/remove/', views.train_queue_remove, name='train_queue_remove'),
    path('treino/block/', views.train_block_problem, name='train_block_problem'),
    path('contests/', views.contests_overview, name='contests_overview'),
    path(
        'contests/snippet/<str:platform>/<str:contest_id>/problems',
        views.contest_problems_snippet,
        name='contest_problems_snippet',
    ),
    path(
        'contests/<str:platform>/<str:contest_id>/snippet/solvers',
        views.contest_solvers_snippet,
        name='contest_solvers_snippet',
    ),
    path(
        'contests/<str:platform>/<str:contest_id>/snippet/solvers_chunk',
        views.contest_solvers_chunk,
        name='contest_solvers_chunk',
    ),
    path('contests/<str:platform>/<str:contest_id>/', views.contest_detail, name='contest_detail'),
]
